"""
Generates a downloadable Word document report from tonight's digest,
including the narrative writeups generated by generate_writeups.py.

Runs after generate_writeups.py. Produces digests/<date>.docx alongside the
existing digests/<date>.md — the .md stays as the quick-scan version, the
.docx is the semi-detailed report meant for actual reading/downloading.
"""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
from db_utils import get_connection

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

DIGESTS_DIR = Path(__file__).parent.parent / "digests"
TABLE_NAME_MAP = {"repo": "repos", "video": "videos", "news": "news"}

SECTION_TITLES = {
    "overlap": "Overlap — Highest on Both Axes",
    "top_substance": "Top Substance",
    "top_trend": "Top Trend",
}


def get_digest_items_by_section(conn, digest_date):
    """
    Re-derives section membership from the digest generation logic's output
    tags. Since generate_digest.py already tagged items with the digest
    date, we re-fetch and re-sort here using the same ranking rules to
    reconstruct which section(s) each item belonged to for display grouping.
    """
    all_items = []
    for content_type, table in TABLE_NAME_MAP.items():
        rows = conn.execute(
            f"""SELECT url, title, content_type, substance_score, substance_reasoning,
                       trend_score, trend_reasoning, writeup
                FROM {table} WHERE included_in_digest LIKE ?""",
            (f'%"{digest_date}"%',),
        ).fetchall()
        for r in rows:
            all_items.append(dict(r))
    return all_items


def is_numeric_trend(item):
    try:
        int(item["trend_score"])
        return True
    except (TypeError, ValueError):
        return False


def classify_sections(items):
    overlap, top_substance, top_trend = [], [], []
    for item in items:
        sub = item["substance_score"] or 0
        trend_ok = is_numeric_trend(item)
        trend = int(item["trend_score"]) if trend_ok else 0
        if sub >= 4 and trend_ok and trend >= 4:
            overlap.append(item)
        elif sub >= trend:  # rough heuristic for display grouping only, not re-ranking
            top_substance.append(item)
        else:
            top_trend.append(item)
    return {"overlap": overlap, "top_substance": top_substance, "top_trend": top_trend}


def add_item(doc, item):
    p = doc.add_paragraph()
    run = p.add_run(item["title"])
    run.bold = True
    run.font.size = Pt(13)

    meta = doc.add_paragraph()
    meta_run = meta.add_run(
        f"{item['content_type'].upper()}  ·  Substance {item['substance_score']}/5"
        + (f"  ·  Trend {item['trend_score']}/5" if is_numeric_trend(item) else "")
    )
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    link_p = doc.add_paragraph()
    link_run = link_p.add_run(item["url"])
    link_run.font.size = Pt(9)
    link_run.font.color.rgb = RGBColor(0x1a, 0x5a, 0xa8)
    link_run.underline = True

    body = doc.add_paragraph()
    body_text = item["writeup"] or "(No writeup generated — GEMINI_API_KEY may not have been set for this run.)"
    body_run = body.add_run(body_text)
    body_run.font.size = Pt(11)

    doc.add_paragraph()  # spacing


def build_document(digest_date, sections):
    doc = Document()

    title = doc.add_heading(f"AI Digest — {digest_date}", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT

    total = sum(len(v) for v in sections.values())
    subtitle = doc.add_paragraph()
    subtitle_run = subtitle.add_run(f"{total} items this week, across repos, videos, and news.")
    subtitle_run.italic = True
    subtitle_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    doc.add_paragraph()

    for key in ("overlap", "top_substance", "top_trend"):
        items = sections[key]
        if not items:
            continue
        doc.add_heading(SECTION_TITLES[key], level=1)
        for item in items:
            add_item(doc, item)

    return doc


def main(digest_date=None):
    if digest_date is None:
        digest_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    conn = get_connection()
    items = get_digest_items_by_section(conn, digest_date)
    conn.close()

    if not items:
        print(f"[warn] no digest items found for {digest_date} — skipping docx generation.")
        return

    sections = classify_sections(items)
    doc = build_document(digest_date, sections)

    DIGESTS_DIR.mkdir(exist_ok=True)
    out_path = DIGESTS_DIR / f"{digest_date}.docx"
    doc.save(str(out_path))
    print(f"Word report written to {out_path} ({len(items)} items)")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", default=None)
    args = parser.parse_args()
    main(args.date)
